// khai báo các name actions
export const FETCH_NHANVIEN = "FETCH_NHANVIEN";
export const FETCH_NHANVIEN_SUCCESS = "FETCH_NHANVIEN_SUCCESS";
export const FETCH_NHANVIEN_ERROR = "FETCH_NHANVIEN_ERROR";