// khai báo các name actions
export const FETCH_DMHUONGDAN = "FETCH_DMHUONGDAN";
export const FETCH_DMHUONGDAN_SUCCESS = "FETCH_DMHUONGDAN_SUCCESS";
export const FETCH_DMHUONGDAN_ERROR = "FETCH_DMHUONGDAN_ERROR";
