export const FETCH_SANPHAM = "FETCH_SANPHAM";
export const FETCH_SANPHAM_SUCCESS = "FETCH_SANPHAM_SUCCESS";
export const FETCH_SANPHAM_ERROR = "FETCH_SANPHAM_ERROR";

export const FETCH_CONGNGHESANXUAT = "FETCH_CONGNGHESANXUAT";
export const FETCH_CONGNGHESANXUAT_SUCCESS = "FETCH_CONGNGHESANXUAT_SUCCESS";
export const FETCH_CONGNGHESANXUAT_ERROR = "FETCH_CONGNGHESANXUAT_ERROR";

export const FETCH_NGUYENVATLIEU = "FETCH_NGUYENVATLIEU";
export const FETCH_NGUYENVATLIEU_SUCCESS = "FETCH_NGUYENVATLIEU_SUCCESS";
export const FETCH_NGUYENVATLIEU_ERROR = "FETCH_NGUYENVATLIEU_ERROR";

export const FETCH_HOACHAT = "FETCH_HOACHAT";
export const FETCH_HOACHAT_SUCCESS = "FETCH_HOACHAT_SUCCESS";
export const FETCH_HOACHAT_ERROR = "FETCH_HOACHAT_ERROR";

export const FETCH_DONVI = "FETCH_DONVI";
export const FETCH_DONVI_SUCCESS = "FETCH_DONVI_SUCCESS";
export const FETCH_DONVI_ERROR = "FETCH_DONVI_ERROR";

export const FETCH_NHIENLIEU = "FETCH_NHIENLIEU";
export const FETCH_NHIENLIEU_SUCCESS = "FETCH_NHIENLIEU_SUCCESS";
export const FETCH_NHIENLIEU_ERROR = "FETCH_NHIENLIEU_ERROR";

export const FETCH_THONGTINHOATDONG = "FETCH_THONGTINHOATDONG";
export const FETCH_THONGTINHOATDONG_SUCCESS = "FETCH_THONGTINHOATDONG_SUCCESS";
export const FETCH_THONGTINHOATDONG_ERROR = "FETCH_THONGTINHOATDONG_ERROR";

export const FETCH_LOAIHOATDONG = "FETCH_LOAIHOATDONG";
export const FETCH_LOAIHOATDONG_SUCCESS = "FETCH_LOAIHOATDONG_SUCCESS";
export const FETCH_LOAIHOATDONG_ERROR = "FETCH_LOAIHOATDONG_ERROR";
