// khai báo các name actions
export const FETCH_TINHTHANH = "FETCH_TINHTHANH";
export const FETCH_TINHTHANH_SUCCESS = "FETCH_TINHTHANH_SUCCESS";
export const FETCH_TINHTHANH_ERROR = "FETCH_TINHTHANH_ERROR";

